=begin
#Security Policy url normalization API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SecurityPolicyUrlNormalizationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SecurityPolicyUrlNormalizationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SecurityPolicyUrlNormalizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurityPolicyUrlNormalizationApi' do
    it 'should create an instance of SecurityPolicyUrlNormalizationApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SecurityPolicyUrlNormalizationApi)
    end
  end

  # unit tests for security_policies_policy_name_url_normalization_get
  # FETCH Information of Security Policy url normalization
  # 
  # @param authorization Login token
  # @param policy_name Policy Name of Security Policy url normalization
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'security_policies_policy_name_url_normalization_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for security_policies_policy_name_url_normalization_put
  # EDIT Information of Security Policy url normalization
  # 
  # @param authorization Login token
  # @param policy_name Policy Name of Security Policy url normalization
  # @param security_policy_url_normalization Body Parameter of Security Policy url normalization
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'security_policies_policy_name_url_normalization_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
