=begin
#Rule Group Server out of band health checks API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::RuleGroupServerOutOfBandHealthChecksBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RuleGroupServerOutOfBandHealthChecksBody' do
  before do
    # run before each test
    @instance = SwaggerClient::RuleGroupServerOutOfBandHealthChecksBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RuleGroupServerOutOfBandHealthChecksBody' do
    it 'should create an instance of RuleGroupServerOutOfBandHealthChecksBody' do
      expect(@instance).to be_instance_of(SwaggerClient::RuleGroupServerOutOfBandHealthChecksBody)
    end
  end
  describe 'test attribute "enable_oob_health_checks"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["On", "Off"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.enable_oob_health_checks = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "interval"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

