=begin
#caching API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CachingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CachingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CachingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CachingApi' do
    it 'should create an instance of CachingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CachingApi)
    end
  end

  # unit tests for services_web_application_name_caching_get
  # FETCH Information of caching
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of caching
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'services_web_application_name_caching_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_web_application_name_caching_put
  # EDIT Information of caching
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of caching
  # @param caching Body Parameter of caching
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_web_application_name_caching_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
