=begin
#instant ssl API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InstantSslApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InstantSslApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InstantSslApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstantSslApi' do
    it 'should create an instance of InstantSslApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InstantSslApi)
    end
  end

  # unit tests for services_web_application_name_instant_ssl_get
  # FETCH Information of instant ssl
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of instant ssl
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'services_web_application_name_instant_ssl_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_web_application_name_instant_ssl_put
  # EDIT Information of instant ssl
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of instant ssl
  # @param instant_ssl Body Parameter of instant ssl
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_web_application_name_instant_ssl_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
