=begin
#Action Policy API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ActionPolicyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ActionPolicyApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ActionPolicyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActionPolicyApi' do
    it 'should create an instance of ActionPolicyApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ActionPolicyApi)
    end
  end

  # unit tests for security_policies_policy_name_action_policies_attack_action_name_get
  # FETCH Information of Action Policy
  # 
  # @param authorization Login token
  # @param policy_name Policy Name of Action Policy
  # @param attack_action_name Attack Action Name of Action Policy
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'security_policies_policy_name_action_policies_attack_action_name_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for security_policies_policy_name_action_policies_attack_action_name_put
  # EDIT Information of Action Policy
  # 
  # @param authorization Login token
  # @param policy_name Policy Name of Action Policy
  # @param attack_action_name Attack Action Name of Action Policy
  # @param action_policy Body Parameter of Action Policy
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'security_policies_policy_name_action_policies_attack_action_name_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for security_policies_policy_name_action_policies_get
  # FETCH Information of Action Policy
  # 
  # @param authorization Login token
  # @param policy_name Policy Name of Action Policy
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'security_policies_policy_name_action_policies_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
