=begin
#Security Policy url normalization API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient

  class SecurityPolicyUrlNormalizationBody
    # Parameter Separators
    attr_accessor :parameter_separators

    # Default Character Set
    attr_accessor :default_charset

    # Detect Response Charset
    attr_accessor :detect_response_charset

    # Apply Double Decoding
    attr_accessor :apply_double_decoding

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'parameter_separators' => :'parameter-separators',
        :'default_charset' => :'default-charset',
        :'detect_response_charset' => :'detect-response-charset',
        :'apply_double_decoding' => :'apply-double-decoding'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'parameter_separators' => :'String',
        :'default_charset' => :'String',
        :'detect_response_charset' => :'String',
        :'apply_double_decoding' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'parameter-separators')
        self.parameter_separators = attributes[:'parameter-separators']
      else
        self.parameter_separators = "Ampersand only"
      end

      if attributes.has_key?(:'default-charset')
        self.default_charset = attributes[:'default-charset']
      else
        self.default_charset = "UTF-8"
      end

      if attributes.has_key?(:'detect-response-charset')
        self.detect_response_charset = attributes[:'detect-response-charset']
      else
        self.detect_response_charset = "No"
      end

      if attributes.has_key?(:'apply-double-decoding')
        self.apply_double_decoding = attributes[:'apply-double-decoding']
      else
        self.apply_double_decoding = "No"
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      parameter_separators_validator = EnumAttributeValidator.new('String', ["Ampersand and Semicolon", "Ampersand only", "Semicolon only"])
      return false unless parameter_separators_validator.valid?(@parameter_separators)
      default_charset_validator = EnumAttributeValidator.new('String', ["ASCII", "ISO-8859-1", "UTF-8", "GBK", "GB2312", "ISO-2022-CN", "HZ", "BIG5", "EUC-TW", "Shift-JIS", "EUC-JP", "ISO-2022-JP", "EUC-KR", "JOHAB", "ISO-2022-KR"])
      return false unless default_charset_validator.valid?(@default_charset)
      detect_response_charset_validator = EnumAttributeValidator.new('String', ["Yes", "No"])
      return false unless detect_response_charset_validator.valid?(@detect_response_charset)
      apply_double_decoding_validator = EnumAttributeValidator.new('String', ["Yes", "No"])
      return false unless apply_double_decoding_validator.valid?(@apply_double_decoding)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] parameter_separators Object to be assigned
    def parameter_separators=(parameter_separators)
      validator = EnumAttributeValidator.new('String', ["Ampersand and Semicolon", "Ampersand only", "Semicolon only"])
      unless validator.valid?(parameter_separators)
        fail ArgumentError, "invalid value for 'parameter_separators', must be one of #{validator.allowable_values}."
      end
      @parameter_separators = parameter_separators
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] default_charset Object to be assigned
    def default_charset=(default_charset)
      validator = EnumAttributeValidator.new('String', ["ASCII", "ISO-8859-1", "UTF-8", "GBK", "GB2312", "ISO-2022-CN", "HZ", "BIG5", "EUC-TW", "Shift-JIS", "EUC-JP", "ISO-2022-JP", "EUC-KR", "JOHAB", "ISO-2022-KR"])
      unless validator.valid?(default_charset)
        fail ArgumentError, "invalid value for 'default_charset', must be one of #{validator.allowable_values}."
      end
      @default_charset = default_charset
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] detect_response_charset Object to be assigned
    def detect_response_charset=(detect_response_charset)
      validator = EnumAttributeValidator.new('String', ["Yes", "No"])
      unless validator.valid?(detect_response_charset)
        fail ArgumentError, "invalid value for 'detect_response_charset', must be one of #{validator.allowable_values}."
      end
      @detect_response_charset = detect_response_charset
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] apply_double_decoding Object to be assigned
    def apply_double_decoding=(apply_double_decoding)
      validator = EnumAttributeValidator.new('String', ["Yes", "No"])
      unless validator.valid?(apply_double_decoding)
        fail ArgumentError, "invalid value for 'apply_double_decoding', must be one of #{validator.allowable_values}."
      end
      @apply_double_decoding = apply_double_decoding
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          parameter_separators == o.parameter_separators &&
          default_charset == o.default_charset &&
          detect_response_charset == o.detect_response_charset &&
          apply_double_decoding == o.apply_double_decoding
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [parameter_separators, default_charset, detect_response_charset, apply_double_decoding].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
