=begin
#load balancing API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::LoadBalancingBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LoadBalancingBody' do
  before do
    # run before each test
    @instance = SwaggerClient::LoadBalancingBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoadBalancingBody' do
    it 'should create an instance of LoadBalancingBody' do
      expect(@instance).to be_instance_of(SwaggerClient::LoadBalancingBody)
    end
  end
  describe 'test attribute "backup_server"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Yes", "No"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.backup_server = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "weight"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

