=begin
#Server API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ServerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ServerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServerApi' do
    it 'should create an instance of ServerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ServerApi)
    end
  end

  # unit tests for services_web_application_name_servers_get
  # FETCH Information of Server
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of Server
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'services_web_application_name_servers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_web_application_name_servers_post
  # ADD Information of Server
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of Server
  # @param server Body Parameter of Server
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_web_application_name_servers_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_web_application_name_servers_server_name_delete
  # DELETE Information of Server
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of Server
  # @param server_name Server Name of Server
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_web_application_name_servers_server_name_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_web_application_name_servers_server_name_get
  # FETCH Information of Server
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of Server
  # @param server_name Server Name of Server
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields 
  # @return [nil]
  describe 'services_web_application_name_servers_server_name_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_web_application_name_servers_server_name_put
  # EDIT Information of Server
  # 
  # @param authorization Login token
  # @param web_application_name Web Application Name of Server
  # @param server_name Server Name of Server
  # @param server Body Parameter of Server
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_web_application_name_servers_server_name_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
